# Generated by Django 3.2.8 on 2021-10-19 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_auto_20211019_1208'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='price',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='customer',
            name='member_ship',
            field=models.CharField(choices=[('S', 'Silver'), ('B', 'Bronze'), ('G', 'Gold')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='member_ship',
            field=models.CharField(choices=[('C', 'Complete'), ('P', 'Pending'), ('F', 'Fail')], default='P', max_length=1),
        ),
    ]
