# Generated by Django 3.2.8 on 2021-10-22 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20211022_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='member_ship',
            field=models.CharField(choices=[('S', 'Silver'), ('G', 'Gold'), ('B', 'Bronze')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('F', 'Fail'), ('P', 'Pending'), ('C', 'Complete')], default='P', max_length=1),
        ),
        migrations.AlterField(
            model_name='product',
            name='collection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='products', to='store.collection'),
        ),
    ]
