# Generated by Django 3.2.8 on 2021-10-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_auto_20211023_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='member_ship',
            field=models.CharField(choices=[('S', 'Silver'), ('G', 'Gold'), ('B', 'Bronze')], default='B', max_length=1),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('F', 'Fail'), ('P', 'Pending'), ('C', 'Complete')], default='P', max_length=1),
        ),
    ]
